# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Endless' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Endless

  target 'EndlessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EndlessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
